{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pgdog.fullname" . }}
  labels:
    {{- include "pgdog.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /
      port: openmetrics
  selector:
    matchLabels:
      {{- include "pgdog.selectorLabels" . | nindent 6 }}
{{- end }}