{{- if .Values.statefulSet.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgdog.fullname" . }}-headless
  labels:
    {{- include "pgdog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "pgdog.selectorLabels" . | nindent 4 }}
  ports:
    - name: pgdog
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    - name: openmetrics
      protocol: TCP
      port: {{ .Values.openMetricsPort }}
      targetPort: {{ .Values.openMetricsPort }}
{{- end }}
