{{- if .Values.tlsGenerateSelfSignedCert }}
{{- $fullname := include "pgdog.fullname" . }}
{{- $cert := genSelfSignedCert $fullname nil (list "localhost" $fullname (printf "%s.%s.svc.cluster.local" $fullname .Release.Namespace)) 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-tls
  labels:
    {{- include "pgdog.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ $cert.Cert | indent 4 }}
  tls.key: |
{{ $cert.Key | indent 4 }}
{{- end }}
